import java.util.Random;

/**
 * Computes some statistics about families in which the parents decide
 * to have children until they have at least one child of each gender.
 * The program expects to get two command-line arguments: an int value
 * that determines how many families to simulate, and an int value
 * that serves as the seed of the random numbers generated by the program.
 * Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main(String[] args) {

		int numFamilies = Integer.parseInt(args[0]);
		double ExpTotal = 0;
		double ExpAvg = 0;
		int child2 = 0;
		int child3 = 0;
		int child4Plus = 0;
		int seed = Integer.parseInt(args[1]);
		Random generator = new Random(seed);

		for (int i = 0; i < numFamilies; i++) {
			boolean b = false;
			boolean g = false;
			int count = 0;
			while (b == false || g == false) {
				// declare a random number either 0 or 1
				int rnd = (int) (generator.nextDouble() * 2);
				count++;
				if (rnd == 0) {
					b = true;
				} else {
					g = true;
				}
			}
			if (count == 2) {
				child2++;
			} else {
				if (count == 3) {
					child3++;
				} else {
					child4Plus++;
				}
			}

			ExpTotal += count;
		}
		ExpAvg = ExpTotal / numFamilies;

		String max = "";
		if ((child2 > child3) && (child2 > child4Plus)) {
			max = "the most common number of children is 2";
		} else {
			if (child3 > child4Plus) {
				max = "the most common number of children is 3";
			} else {
				max = "the most common number of children is 4 or more";
			}
		}
		System.out.println("Average: " + ExpAvg + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + child2);
		System.out.println("Number of families with 3 children: " + child3);
		System.out.println("Number of families with 4 or more children: " + child4Plus);
		System.out.println(max);
		// Gets the two command-line arguments
		// int T = Integer.parseInt(args[0]);
		// int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
		// Random generator = new Random(seed);
		// double rnd = generator.nextDouble();

		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.

	}
}
